### ISSUE TITLE
Compilation error after bumping EXLA to 0.11

### ISSUE THREAD

**Issue by FelonEkonom** [elixir-nx/nx#1725]
After bumping EXLA to `0.11` in my project, I got following error over and over again:
```
==> exla 
 EXLA_CPU_ONLY is set, skipping nvcc step 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_cuda.cc -o 
cache/0.11.0/objs/exla_cuda.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla.cc -o 
cache/0.11.0/objs/exla.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_client.cc -o 
cache/0.11.0/objs/exla_client.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_mlir.cc -o 
cache/0.11.0/objs/exla_mlir.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c 
c_src/exla/custom_calls/runtime_callback.cc -o 
cache/0.11.0/objs/custom_calls/runtime_callback.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c c_src/exla/ipc.cc -o 
cache/0.11.0/objs/ipc.o 

 g++ -fPIC -I/usr/lib/erlang/erts-15.2.7/include 
-I<PATH_TO_HOME>/<PROJECT_DIR>/deps/fine/c_include 
-Icache/xla_extension/include -Wall -Wno-sign-compare 
-Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment 
-std=c++17 -w -DNDEBUG -O3 -c 
c_src/exla/custom_calls/runtime_callback_bridge.cc -o 
cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o 

 g++ cache/0.11.0/objs/exla.o cache/0.11.0/objs/exla_client.o 
cache/0.11.0/objs/exla_mlir.o cache/0.11.0/objs/ipc.o 
cache/0.11.0/objs/custom_calls/runtime_callback.o 
cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o 
cache/0.11.0/objs/exla_cuda.o -o cache/libexla.so 
-Lcache/xla_extension/lib -lxla_extension -shared -fvisibility=hidden 
-Wl,-rpath,'$ORIGIN/xla_extension/lib' 
 /usr/bin/ld: cache/0.11.0/objs/exla_client.o: in function `fine::__private__::init_atoms(enif_environment_t*)': 

 exla_client.cc:(.text+0xd70): multiple definition of 
`fine::__private__::init_atoms(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xdf0): first defined here 
 /usr/bin/ld: cache/0.11.0/objs/exla_client.o: in function `fine::__private__::init_resources(enif_environment_t*)': 

 exla_client.cc:(.text+0xe20): multiple definition of 
`fine::__private__::init_resources(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xea0): first defined here 
 /usr/bin/ld: cache/0.11.0/objs/exla_mlir.o: in function `fine::__private__::init_atoms(enif_environment_t*)': 

 exla_mlir.cc:(.text+0x0): multiple definition of 
`fine::__private__::init_atoms(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xdf0): first defined here 
 /usr/bin/ld: cache/0.11.0/objs/exla_mlir.o: in function `fine::__private__::init_resources(enif_environment_t*)': 

 exla_mlir.cc:(.text+0xb0): multiple definition of 
`fine::__private__::init_resources(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xea0): first defined here 

 /usr/bin/ld: cache/0.11.0/objs/custom_calls/runtime_callback.o: in 
function `fine::__private__::init_atoms(enif_environment_t*)': 

 runtime_callback.cc:(.text+0x960): multiple definition of 
`fine::__private__::init_atoms(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xdf0): first defined here 

 /usr/bin/ld: cache/0.11.0/objs/custom_calls/runtime_callback.o: in 
function `fine::__private__::init_resources(enif_environment_t*)': 

 runtime_callback.cc:(.text+0xa10): multiple definition of 
`fine::__private__::init_resources(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xea0): first defined here 

 /usr/bin/ld: cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o: 
in function `fine::__private__::init_atoms(enif_environment_t*)': 

 runtime_callback_bridge.cc:(.text+0xa0): multiple definition of 
`fine::__private__::init_atoms(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xdf0): first defined here 

 /usr/bin/ld: cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o: 
in function `fine::__private__::init_resources(enif_environment_t*)': 

 runtime_callback_bridge.cc:(.text+0x150): multiple definition of 
`fine::__private__::init_resources(enif_environment_t*)'; 
cache/0.11.0/objs/exla.o:exla.cc:(.text+0xea0): first defined here 
 collect2: error: ld returned 1 exit status 
 make: *** [Makefile:109: cache/libexla.so] Error 1 

 could not compile dependency :exla, "mix compile" failed. Errors may 
have been logged above. You can recompile this dependency with "mix 
deps.compile exla --force", update it with "mix deps.update exla" or 
clean it with "mix deps.clean exla"
```

I had to manually add `inline` to `init_atoms` and `init_resources` definitions in `deps/fine/c_include/fine.cpp` to make it work

**Comment by kipcole9** [comment]
I *think* I'm seeing the same issue on MacOS. 

* MacOS 15.6.1 (Sequoia)
* Clang version 15.0.0 (clang-1500.3.9.4)

```
==> exla
Unpacking /Users/kip/Library/Caches/xla/0.10.0/download/xla_extension-0.10.0-aarch64-darwin-cpu.tar.gz into /Users/kip/Development/exla_test/deps/exla/cache
EXLA_CPU_ONLY is not set, checking for nvcc availability
CUDA is not available.
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_client.cc -o cache/0.11.0/objs/exla_client.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/ipc.cc -o cache/0.11.0/objs/ipc.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_mlir.cc -o cache/0.11.0/objs/exla_mlir.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla.cc -o cache/0.11.0/objs/exla.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/exla_cuda.cc -o cache/0.11.0/objs/exla_cuda.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/custom_calls/runtime_callback_bridge.cc -o cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o
c++ -O2 -g -fno-stack-check -fPIC -I/Users/kip/.local/share/mise/installs/erlang/28.3.1/erts-16.2/include -I/Users/kip/Development/exla_test/deps/fine/c_include -Icache/xla_extension/include -Wall -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-comment -std=c++17 -w -DNDEBUG -O3 -c c_src/exla/custom_calls/runtime_callback.cc -o cache/0.11.0/objs/custom_calls/runtime_callback.o
c++ cache/0.11.0/objs/exla.o cache/0.11.0/objs/exla_client.o cache/0.11.0/objs/exla_mlir.o cache/0.11.0/objs/ipc.o cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o cache/0.11.0/objs/custom_calls/runtime_callback.o cache/0.11.0/objs/exla_cuda.o -o cache/libexla.so -Lcache/xla_extension/lib -lxla_extension -shared -fvisibility=hidden -flat_namespace -undefined dynamic_lookup -rpath @loader_path/xla_extension/lib
duplicate symbol '__ZN4fine11__private__10init_atomsEP18enif_environment_t' in:
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla_mlir.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/custom_calls/runtime_callback.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla_client.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla.o
duplicate symbol '__ZN4fine11__private__14init_resourcesEP18enif_environment_t' in:
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla_mlir.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/custom_calls/runtime_callback_bridge.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/custom_calls/runtime_callback.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla_client.o
    /Users/kip/Development/exla_test/deps/exla/cache/0.11.0/objs/exla.o
ld: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [cache/libexla.so] Error 1
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla --force", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"
```

**Comment by polvalente** [comment]
What is the version of `fine` being used locally? There was a recent `fine` release and I want to eliminate that as the culprit. Fix could be as easy as forcing `0.1.4` as the version

**Comment by kipcole9** [comment]
I'm seeing the same issue on  `exia` `0.11.0` with both `fine` `0.1.4` and `0.1.5` (MacOS).  I just confirmed I am able to compile successfully with `exla` `0.10.0` with both `0.1.4` and `0.1.5` versions of `fine`.

**Comment by polvalente** [comment]
Just as a sanity check, can you confirm that forcing `fine 0.1.4` and using `EXLA_FORCE_REBUILD=true mix compile` results in this error?
Sometimes we can end up with some caches and that flag helps bypass them.

**Comment by FelonEkonom** [comment]
I have `fine 0.1.4` in mix.lock and I tried to clear cache before I fixed it locally, but I don't want to recompile right now, after I managed to make it work

**Comment by polvalente** [comment]
@FelonEkonom since you already had fine 0.1.4 in you mix.lock, that also serves as the sanity check!

**Comment by kipcole9** [comment]
I *think* @FelonEkonom may have patched the code per his comment above:
> I had to manually add inline to init_atoms and init_resources definitions in deps/fine/c_include/fine.cpp to make it work

**Comment by polvalente** [comment]
@kipcole9 yes, I meant that it is indeed broken in fine 0.1.4 and it wasn't a silent upgrade of that that caused the issue.

Likely related to external tooling, as we also got a separate issue on compilation warnings

**Comment by kipcole9** [comment]
OK, I've done quite a few more loops now and I can reliably build with nx/exla 0.11.0 with fine 0.1.4., but reliably gets the ld error on 0.1.5.

**Comment by laszlokorte** [comment]
downgrading to fine 0.1.4 did it for me as well.

**Comment by jonatanklosko** [comment]
Fixed in fine 0.1.6, sorry about that!

**Comment by polvalente** [comment]
> Fixed in fine 0.1.6, sorry about that!

@jonatanklosko don't worry, it's... fine!

Thanks for the fix :)
