### PR TITLE
Add sigil for tensors

### PR DESCRIPTION
**Pull request by dannote**
This PR adds `~M[]` sigil that evaluates to `#Nx.Tensor<>` as discussed in #358, but with type in the modifier.

I've added conditional compilation since support for digits in sigils was just merged to Elixir (elixir-lang/elixir#11283).

### CODE REVIEW

File: nx/lib/nx.ex [hunk 1]
```diff
@@ -8451,6 +8451,43 @@ defmodule Nx do
     )
   end
 
+  ## Sigils
+
+  if Version.match?(System.version(), ">= 1.13.0-dev") do
+    defmacro sigil_M({:<<>>, _meta, [string]}, modifiers) do
```
Comment (polvalente) [inline nx/lib/nx.ex:8457]: Nice work! 

This implementation only supports a literal tensor, without resolving interpolations. Is this intentional?
Perhaps a better error could be raised in such case. For now the behavior is:

```elixir
iex(7)> x = 1       
1
iex(8)> ~M[#{x} 2]
** (ArgumentError) cannot infer the numerical type of nil
    (nx 0.1.0-dev) lib/nx/type.ex:110: Nx.Type.infer/2
    (elixir 1.13.0-dev) lib/enum.ex:2394: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nx 0.1.0-dev) lib/nx/type.ex:98: Nx.Type.infer/1
    (nx 0.1.0-dev) expanding macro: Nx.sigil_M/2
    iex:8: (file)
```

Comment (dannote) [reply nx/lib/nx.ex:8457]: Yes, this is intentional. I followed the convention in [built-in sigils](https://hexdocs.pm/elixir/1.12/Kernel.html#sigil_C/2) and used uppercase "M" to indicate this behaviour.

Comment (polvalente) [reply nx/lib/nx.ex:8457]: I would try to raise a more semantic message then. Otherwise, this seems good :)

Comment (polvalente) [reply nx/lib/nx.ex:8457]: It seems that for non-numerical values the current message is fine:

```elixir
iex(11)> ~M[1 2 "a" 3]
** (ArgumentError) cannot infer the numerical type of "a"
    (nx 0.1.0-dev) lib/nx/type.ex:110: Nx.Type.infer/2
    (elixir 1.13.0-dev) lib/enum.ex:2394: Enum."-reduce/3-lists^foldl/2-0-"/3
    (nx 0.1.0-dev) lib/nx/type.ex:98: Nx.Type.infer/1
    (nx 0.1.0-dev) expanding macro: Nx.sigil_M/2
    iex:11: (file)
```

Comment (polvalente) [reply nx/lib/nx.ex:8457]: I'm not sure if this is also a predicted edge case:

```elixir
iex(11)> x = 1
1
iex(12)> ~M[1 2 x 3]  
warning: variable "x" does not exist and is being expanded to "x()", please use parentheses to remove the ambiguity or change the variable name
  nofile:1

** (CompileError) nofile:1: undefined function x/0 (there is no such import)
    (elixir 1.13.0-dev) lib/code.ex:404: Code.validated_eval_string/3
    (nx 0.1.0-dev) lib/nx.ex:8486: anonymous fn/1 in Nx.binary_to_numbers/1
    (elixir 1.13.0-dev) lib/enum.ex:1591: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.13.0-dev) lib/enum.ex:1591: Enum."-map/2-lists^map/1-0-"/2
    (nx 0.1.0-dev) lib/nx.ex:8486: anonymous fn/2 in Nx.binary_to_numbers/1
    (nx 0.1.0-dev) expanding macro: Nx.sigil_M/2
```

It seems that the sigil is trying to expand the variable on a "raw" env instead of the caller env

Comment (polvalente) [reply nx/lib/nx.ex:8457]: Perhaps instead of using Code.eval_string, you could try to parse it with Integer.parse and Float.parse like so:

```elixir
defp binary_to_numbers(string) do
      for row <- String.split(string, "\n", trim: true) do
        row
        |> String.split(" ", trim: true)
        |> Enum.map(fn str ->
          case Integer.parse(str) do
            {int, ""} ->
              int

            _ ->
              case Float.parse(str) do
                {float, ""} -> float
                _ -> raise ArgumentError, "expected a numerical value for tensor, got #{str}"
              end
          end
        end)
      end
    end
```

This conditional structure is perhaps not ideal, but you can take this as a starting point. Maybe a `with` statement could be of use here.

Comment (dannote) [reply nx/lib/nx.ex:8457]: I tried to avoid it:
```elixir
defp binary_to_numbers(string) do
  for row <- String.split(string, "\n", trim: true) do
    row
    |> String.split(" ", trim: true)
    |> Stream.map(&Code.eval_string/1)
    |> Enum.map(fn
      {number, _} when is_number(number) -> number
      _ -> raise ArgumentError, "non-numerics and interpolations are not allowed"
    end)
  end
end
```

But there was another bad side effect:
```
iex(3)> ~M[x 2]
warning: variable "x" does not exist and is being expanded to "x()", please use parentheses to remove the ambiguity or change the variable name
  nofile:1
```

So I'll follow your advice, thanks :)

Comment (dannote) [reply nx/lib/nx.ex:8457]: I think I found a more concise way

File: nx/lib/nx.ex [hunk 2]
```diff
@@ -8451,6 +8451,53 @@ defmodule Nx do
     )
   end
 
+  ## Sigils
+
+  if Version.match?(System.version(), ">= 1.13.0-dev") do
```
Comment (josevalim) [inline nx/lib/nx.ex:8456]: We don't need this check. We can always define the sigil but we will note in the docs the type modifiers require 1.13.

File: nx/test/nx_test.exs [hunk 3]
```diff
@@ -1628,4 +1628,69 @@ defmodule NxTest do
...
+        assert_raise(
+          ArgumentError,
+          "expected a numerical value for tensor, got x",
+          fn ->
+            defmodule Test3 do
+              import Nx
+
+              def case do
+                unquote(Code.string_to_quoted!("~M[1 2 x 4]u8"))
+              end
```
Comment (josevalim) [inline nx/test/nx_test.exs:1689]:
```suggestion
              ~M[1 2 x 4]u8
```

This should be enough to test it!

File: nx/test/nx_test.exs [hunk 4]
```diff
@@ -1628,4 +1628,69 @@ defmodule NxTest do
...
+        assert ~M[1.0 2  3
+                  11  12 13] == Nx.tensor([[1.0, 2, 3], [11, 12, 13]])
+      end
+
+      test "evaluates with proper type" do
+        defmodule Test do
+          import Nx
+
+          def case1 do
+            unquote(Code.string_to_quoted!("~M[1 2 3 4]f32"))
```
Comment (josevalim) [inline nx/test/nx_test.exs:1651]: The unquote should not be needed here.

File: nx/test/nx_test.exs [hunk 5]
```diff
@@ -1628,4 +1628,69 @@ defmodule NxTest do
...
+      test "evaluates to tensor" do
+        import Nx
+
+        assert ~M[-1 2 3 4] == Nx.tensor([-1, 2, 3, 4])
+        assert ~M[1
+                  2
+                  3
+                  4] == Nx.tensor([[1], [2], [3], [4]])
+        assert ~M[1.0 2  3
+                  11  12 13] == Nx.tensor([[1.0, 2, 3], [11, 12, 13]])
```
Comment (josevalim) [inline nx/test/nx_test.exs:1643]: Please don't forget to format this file. :)

**Review by josevalim — COMMENTED** [review]
The implementation looks great! I have dropped only some minor comments. :)

File: nx/test/nx_test.exs (hunk 4 above)
Comment (dannote) [reply nx/test/nx_test.exs:1651]: It won't compile on `1.12` then:

```elixir
== Compilation error in file test/nx_test.exs ==
** (SyntaxError) test/nx_test.exs:1688:29: syntax error before: "8"
    (elixir 1.12.0) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.0) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Comment (josevalim) [reply nx/test/nx_test.exs:1651]: I see. So the whole test can be `Code.eval_string("import Nx; ~M[1 2 3 4]f32")`. You don't need the wrapper module. :)

File: nx/test/nx_test.exs (hunk 5 above)
Comment (dannote) [reply nx/test/nx_test.exs:1643]: That's how it looks after running `mix formatter`, I double-checked :)

File: nx/test/nx_test.exs [hunk 6]
```diff
@@ -1628,4 +1628,51 @@ defmodule NxTest do
                )
     end
   end
+
+  if Version.match?(System.version(), ">= 1.13.0-dev") do
```
Comment (josevalim) [inline nx/test/nx_test.exs:1632]: Move this conditional to only wrap around the tests that use eval and therefore requires the modifiers.

File: nx/test/nx_test.exs (hunk 5 above)
Comment (josevalim) [reply nx/test/nx_test.exs:1643]: Interesting. It may be a formatter bug. :)

File: nx/lib/nx.ex [hunk 7]
```diff
@@ -8451,6 +8451,51 @@ defmodule Nx do
     )
   end
 
+  ## Sigils
+
+  defmacro sigil_M({:<<>>, _meta, [string]}, modifiers) do
```
Comment (josevalim) [inline nx/lib/nx.ex:8456]: Please don’t forget documentation. :)

File: nx/test/nx_test.exs [hunk 8]
```diff
@@ -1628,4 +1628,51 @@ defmodule NxTest do
                )
     end
   end
+
+  describe "sigil" do
+    test "evaluates to tensor" do
+      import Nx
+
+      assert ~M[-1 2 3 4] == Nx.tensor([-1, 2, 3, 4])
```
Comment (josevalim) [inline nx/test/nx_test.exs:1636]: I have been thinking more about this and it seems to be impossible to specify a tensor that is a single row with multiple columns. Given the sigil is called `~M`, maybe this should always be a matrix? And we can introduce `~V` if we want to support vectors later on?

File: nx/lib/nx.ex [hunk 9]
```diff
@@ -8451,6 +8451,86 @@ defmodule Nx do
...
   end
 
+  ## Sigils
+
+  @doc """
+  A convenient `~M` sigil for building matrices.
+
+  ## Examples
+
+      import Nx
```
Comment (josevalim) [inline nx/lib/nx.ex:8461]:
```suggestion
  Before using sigils, you must first import them:

      import Nx, only: [sigil_M: 2]

  If you are using Elixir v1.13, then you can also write:

      import Nx, only: :sigils

  Then you use the sigil to create matrices:
```

File: nx/test/nx_test.exs (hunk 8 above)
Comment (dannote) [reply nx/test/nx_test.exs:1636]: Good point! Can I add `~V[-1 2 3 4]` as equivalent of `Nx.tensor([-1, 2, 3, 4])` now?

Comment (josevalim) [reply nx/test/nx_test.exs:1636]: Sure!

File: nx/lib/nx.ex [hunk 10]
```diff
@@ -8451,6 +8451,128 @@ defmodule Nx do
     )
   end
 
+  ## Sigils
+
+  @doc """
+  A convenient `~M` sigil for building matrices.
```
Comment (josevalim) [inline nx/lib/nx.ex:8457]:
```suggestion
  A convenient `~M` sigil for building matrices (two-dimensional tensors).
```

File: nx/lib/nx.ex [hunk 11]
```diff
@@ -8451,6 +8451,128 @@ defmodule Nx do
...
+  You can specify the vector type:
+
+      iex> import Nx
+      iex> ~V[0.1 0.2 0.3 0.4]f16
+      #Nx.Tensor<
+        f16[4]
+        [0.0999755859375, 0.199951171875, 0.300048828125, 0.39990234375]
+      >
+
+  """
```
Comment (josevalim) [inline nx/lib/nx.ex:8531]: I have pushed some improvements to `~M` docs, can you please mirror them here? :)

File: nx/lib/nx.ex [hunk 12]
```diff
@@ -8451,6 +8451,128 @@ defmodule Nx do
...
+  defmacro sigil_V({:<<>>, _meta, [string]}, modifiers) do
+    string
+    |> binary_to_numbers
+    |> hd()
```
Comment (josevalim) [inline nx/lib/nx.ex:8535]: We should assert it is only a single row and raise otherwise.

File: nx/lib/nx.ex (hunk 11 above)
Comment (dannote) [reply nx/lib/nx.ex:8531]: Ooops

**Review by josevalim — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
